# Generated by Django 4.1.3 on 2022-11-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skil',
            field=models.ManyToManyField(blank=True, to='school.skill', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skil',
            field=models.ManyToManyField(blank=True, to='school.skill', verbose_name='Skills'),
        ),
    ]
