# Generated by Django 4.1.3 on 2022-11-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('change_name', 'can change name of product'),)},
        ),
    ]
