# Generated by Django 4.1.3 on 2022-11-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
